name: Template Repo Sync

on:
  # Trigger every 1st day of the Month
  schedule:
  - cron:  "0 0 1 * *"

  # Trigger manually
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Template Sync Action
        uses: AndreasAugustin/actions-template-sync@v0.5.3-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: ${{ secrets.SOURCE_REPO_PATH }}  # Add the Source Repo to Secrets
          upstream_branch: main
          pr_title: Sync Template Repo
          is_dry_run: false
